# Site settings
title: Yordan Reyes
email: reyes.yordan@gmail.com
description: "Repositorio de Aplicaciones."
baseurl: ""
url: "http://www.yordanreyes.wordpress.com"
twitter_username: yordanbtc

# Build settings
markdown: kramdown
permalink: pretty

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "post"
    values:
      layout: "post"
